---
- hosts: all
  gather_facts: no
  tasks:
    - name: Ansible ping - try to connect to host - Gitops test
      ping:
      register: pong

    - name: Print ping result
      debug:
        msg: "{{ pong }}"
