---
- hosts: all
  gather_facts: no
  
  tasks:
    - name: Check disk usage
      shell: df -h | awk ' { print "Disk Usage:"" " $1 " " $3"/"$2" ""("$5")" } '
      register: linuxdf

    - name: Print disk usage
      debug:
        msg: "System {{ inventory_hostname }} disk usage {{ linuxdf.stdout_lines }}"