---
- hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Pull Nginx Docker image
      docker_image:
        name: nginx
        source: pull

    - name: Create volume for Nginx
      docker_volume:
        name: nginx-data
        driver: local

    - name: Start Nginx container
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
        volumes:
          - "nginx-data:/usr/share/nginx/html:ro"
