---
- name: Configure Nginx container and AB Testing
  hosts: all
  gather_facts: no
  become: yes
  vars:
    nginx_image: nginx:latest
    nginx_container_name: nginx
    nginx_html_volume: nginx-html
    nginx_html_path: /usr/share/nginx/html
    nginx_conf_volume: nginx-conf
    nginx_conf_path: /etc/nginx/
    nginx_conf_file: /var/lib/docker/volumes/nginx-conf/_data/nginx.conf
    nginx_ab_test_percentage: 80

  tasks:
    - name: Pull Nginx docker image
      docker_image:
        name: "{{ nginx_image }}"
        source: pull

    - name: Create volume for Nginx
      docker_volume:
        name: "{{ item }}"
        driver: local
      with_items:
        - "{{ nginx_html_volume }}"
        - "{{ nginx_conf_volume }}"

    - name: Ensure Nginx container is running
      docker_container:
        name: "{{ nginx_container_name }}"
        image: "{{ nginx_image }}"
        state: present     
        ports:
          - "8888:80"
        volumes:
          - "{{ nginx_html_volume }}:{{ nginx_html_path }}:ro"
          - "{{ nginx_conf_volume }}:{{ nginx_conf_path }}:ro"

    - name: Configure Nginx AB testing percentage
      copy:
        src: ab_testing_split_client.conf
        dest: "{{ nginx_conf_file }}"
      notify: Restart Nginx container

  handlers:
    - name: Restart Nginx container
      docker_container:
        name: "{{ nginx_container_name }}"
        state: started
        restart_policy: always
