# =======================================================================
# Version:          v0.1 - September 16, 2023
# Author:           Weithenn Wang (weithenn at weithenn.org)
# Lab Environment:  Ansible AWX 17.1.0
# description:      Send mail from Gmail SMTP
# =======================================================================

---
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    Gmail_SMTP: 'smtp.gmail.com'

  tasks:
    - name: Sending an e-mail using Gmail SMTP servers
      mail:
        host: "{{ Gmail_SMTP }}"
        port: 587
        username: "{{ Gmail_username }}"
        password: "{{ Gmail_password}}"
        to: "{{ Gmail_adddress }}"
        subject: Can't not SSH to "{{ inventory_hostname }}"
        body: Can't not SSH to "{{ inventory_hostname }}"
      register: sending_email

    - name: Print sending an e-mail result
      debug:
        var: sending_email
