# =======================================================================
# Version:          0.1 - 2020/07/08
# Author:           Weithenn Wang (weithenn at weithenn.org)
# Lab Environment:  Ansible AWX 13.0.0
#                   vCenter Server 6.7 Update 3
# description:      Get the vCenter Server credential and information
# =======================================================================

---
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    vmware:
      vcsa_host: '{{ lookup("env", "VMWARE_HOST") }}'
      vcsa_username: '{{ lookup("env", "VMWARE_USER") }}'
      vcsa_password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      vcsa_certificate: '{{ lookup("env", "VMWARE_VALIDATE_CERTS") }}'

  tasks:
    - name: Print vCenter Server credential
      debug:
        var: vmware

    - name: Get vCenter Server information
      vmware_about_info:
        validate_certs: no
        hostname: "{{ vcsa_host }}"
        username: "{{ vcsa_username }}"
        password: "{{ vcsa_password }}"
      register: vcsa_info

    - name: Print vCenter Server information
      debug:
        var: vcsa_info