# =======================================================================
# Version:          0.1 - 2020/07/08
# Author:           Weithenn Wang (weithenn at weithenn.org)
# Lab Environment:  Ansible AWX 13.0.0
#                   vCenter Server 6.7 Update 3
# description:      Get the vCenter Server credential
# =======================================================================

---
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    vmware:
      host: '{{ lookup("env", "VMWARE_HOST") }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      certificate: '{{ lookup("env", "VMWARE_VALIDATE_CERTS") }}'
  
  tasks:
    - name: Get the vCenter Server credential
      debug:
        var: vmware