---
- hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - debug:
        msg:
          - '{{ lookup("env", "VMWARE_HOST") }}'
          - '{{ lookup("env", "VMWARE_USER") }}'
          - '{{ lookup("env", "VMWARE_PASSWORD") }}'
          - '{{ lookup("env", "VMWARE_VALIDATE_CERTS") }}'
